### ISSUE TITLE
Why lasem using pdfTex, then running lsm-test?

### ISSUE THREAD

**Issue by Borelmar** [LasemProject/lasem#13]
At the output of the test I get three files: t-out.png, t.png t.xml.
The t-out.png:
![t-out](https://github.com/LasemProject/lasem/assets/93738606/f18e9c9d-a778-485d-9e34-81ba61aed490)
And t.png:
![t](https://github.com/LasemProject/lasem/assets/93738606/5e707b8f-e6b9-4b03-9b2e-3b1f738ca5e4)
Did I understand correctly - pdfTex is used to generate t.png?
Shouldn't lasem do this itself?

**Comment by EmmanuelP** [comment]
Hi,

Lasem is actually using latex + dvips + convert, but this is for the a reference image in lsm-test. *-out.png files contain the laser rendering, which shows in your case your installation is missing a font.
