### ISSUE TITLE
Merging changes from mjakeman/lasem

### ISSUE THREAD

**Issue by mjakeman** [LasemProject/lasem#2]
Hi,

I've been maintaining my own fork of Lasem under the assumption that upstream development had stopped (see: https://github.com/mjakeman/lasem/issues/23).

It has a few additional features/changes on top of this repo:
 * An independent port to meson (not as robust as the one here)
 * CI Pipeline
 * Demo application integrating lasem into gtk4
 * Flatpak manifest for one-click building the demo with gnome-builder
 * Documentation using gi-docgen (hosted at https://www.mattjakeman.com/lasem)

Would you be open to integrating some of the above changes? I'd like to discontinue my fork and converge around this one if you are agreeable.

Thanks! :)

**Comment by EmmanuelP** [comment]
Hi Matt,

I'm not working much on lasem lately, but I'm still interested in code contribution or bug reports. I will promptly review and integrate merge requests.

Cheers.

**Comment by EmmanuelP** [comment]
I have ported the documentation build to gi-docgen based on another project I'm maintaining, and enabled a linux CI pipeline.

The documentation area also include the rendering of the test suite using lsm-test.

I'm leaving the issue open, as I'm interrested in the gtk4 based demo.
